Trello API Implementálása
Balage666/afp1_CS_10_00_nagy_projekt pull request #59
Opened 2023-12-07 17:18 UTC by Fecsk3

Trello kártya, lista készítő oldalnak a megírása, valamint a kártyákat mozgató felület létrehozása

2023-12-12 16:42 UTC, BirGer05 requested changes
Nem tudom futtatni a szervert

2023-12-12 16:42 UTC, BirGer05 commented on App/AFP1_Nagy_Project/main/index/views.py
> +import requests
Ez miatt nem tudom el indítani a servert

2023-12-14 09:37 UTC, Fecsk3 reviewed
Átnéztem, működik

2023-12-14 09:38 UTC, BirGer05 approved these changes

2023-12-14 09:59 UTC, merged